### ISSUE TITLE
Wrapped Windows Binaries panic exit when they are cryptographically signed

### ISSUE THREAD

**Issue by dwimberger** [Systemcluster/wrappe#10]
**Bug description**

Wrapped binaries on Windows are broken after they are cryptographically signed. The executable will always abort with the following error:

```
panicked at startpe/src/main.rs:98:9:
file signature is invalid
```

Cryptographic Signature is shown as valid by Windows.

**Reproduction steps**

1. Wrap a windows binary with wrappe
2. Execute the binary (if you are allowed to run unsigned binaries at all) => Works
3. Sign the windows binary (Windows Code Signing) 
4. Execute the binary => Panic Exit with above error (stored in a txt file)

**Comment by Systemcluster** [comment]
Thanks for the report! This issue is caused by SignTool adding its file signature data at the end of the executable, while the wrappe runner expects its own metadata at the end. This should be relatively simple to work around by searching for it when it's not found there.
I'll release an update in the coming days with that change.

**Comment by Systemcluster** [comment]
Signed Windows binaries now work with release `1.0.2`.
